name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19' # The Go version to download (if necessary) and use.
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build .
      - name: Test
        run: go test .
      - name: Build container
        run: docker build -t githubactionstest .
      - name: Login to registry
        env:
          action_secret: ${{ secrets.ACTION_SECRET }}
        run: echo $action_secret | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      - name: Push to registry
        run: docker push ghcr.io/${{ github.repository }}/:latest