name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: ['master']
env:
  REGISTRY: ghcr.io
  ghcr_user: ${{ github.actor }}
  CR_PAT: ${{ secrets.ACTION_SECRET }}
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19' # The Go version to download (if necessary) and use.
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build .
      - name: Test
        run: go test .
        
      - name: Log in to the Container registry
        run: echo "$CR_PAT" | docker login ghcr.io -u "$ghcr_user" --password-stdin
